name: Mein CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout-Code
      uses: actions/checkout@v2

    - name: Ausführen des Shell-Skripts
      run: |
        chmod +x mein_script.sh
        ./mein_script.sh

