name: Tic Tac Toe Game CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout-Code
      uses: actions/checkout@v2

    - name: Setze Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x12.0'

    - name: Installiere Python-Abhängigkeiten
      run: |
        python -m pip install --upgrade pip

    - name: Ausführen des Tic Tac Toe Python-Skripts
      run: python code_tictactoe/tictactoe_ccd.py

